import { LAYOUT } from "../../../layout";

export const MONTH = {
  WIDTH: LAYOUT.WIDTH,
  BLOCK_GAP: LAYOUT.BLOCK_GAP,
  BLOCK_HEADER_HEIGHT: LAYOUT.BLOCK_HEADER_HEIGHT,
  DAY_WIDTH: LAYOUT.DAY_WIDTH,
  DAY_HEADER_HEIGHT: LAYOUT.DAY_HEADER_HEIGHT,
  H_GAP: LAYOUT.H_GAP,
  ROW_TOP: LAYOUT.ROW_TOP,
  ROW_HEIGHT: LAYOUT.ROW_HEIGHT,
  BAR_GAP: LAYOUT.BAR_GAP,
  SUMMARY_GAP: LAYOUT.SUMMARY_GAP,
} as const;
